[package]
name = "client_1"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
# Cli builder
clap = "4.0.8"
# Error handling
eyre = "0.6"
color-eyre = "0.6"
# Requests
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
# Logging
tracing = "0.1"
tracing-subscriber = "0.3"
# Async Traits
async-trait = "0.1"
# gRPC & Protocol buffers
tonic = "0.9"
prost = "0.11"

[build-dependencies]
tonic-build = { version = "0.9", features = ["prost"] }